name: AJ_Grid_test
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14578
title: Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010300'
    - '#3a352f'
    - '#fefef9'
    - '#736a65'
    - '#a1a294'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.7283932499121875
purpose: []
