name: AJ_Grid_test
favicon: null
layout_spectrum: 0.92502
typography_spectrum: 0.24673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080904'
    - '#f3d9dc'
    - '#2c303b'
    - '#b59598'
    - '#70636d'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.7283932499121875
purpose: []
